# Build environment
# -----------------
FROM golang:1.13-alpine
WORKDIR /go-with-docker

RUN apk update && apk add --no-cache gcc musl-dev git

COPY . .

RUN go build -ldflags '-w -s' -a -o ./bin/app ./cmd/app

# Deployment environment
# ----------------------
FROM alpine
RUN apk update && apk add --no-cache bash

COPY --from=build-env /go-with-docker/bin/app /go-with-docker/
EXPOSE 8080
CMD ["/go-with-docker/bin/app"]