version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    depends_on:
      - db
    command: [ "/usr/local/bin/go-with-docker/wait-for-mysql.sh", "db", "/usr/local/bin/go-with-docker/init.sh" ]
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"

  db:
    build: ./docker/mariaDB/
    environment:
      MYSQL_ROOT_PASSWORD: myapp_root_pass
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_pass
      ports: 3306:3306
      restart: always